version: '3'
services:
  elixir:
    build: ./
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - postgresql
    links:
      - postgresql
    entrypoint: ./entrypoint.sh
  postgresql:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flip_a_coin_prod
    volumes:
     - ${PWD}/db:/var/lib/postgresql/data


